### PR TITLE
Basic auth support

### PR DESCRIPTION
**Pull request by emilianomaccaferri**
Hello there! 
Thanks for the great work, I happened to read about the project on Reddit a few days ago while I was searching for a rqlite crate for my uni project.

I added basic auth support because my nodes are secured as described [here](https://rqlite.io/docs/guides/security/#example-configuration-file).

Happy to help,
Emiliano

### CODE REVIEW

**Comment by tomvoet** [comment]
Hi,
First of all, thanks a lot!
I added error handling for this functionality and updated the builder function to make the API clearer.
Please let me know if there's anything else you'd like to discuss or add :)
Otherwise, I plan to merge this soon!

**Comment by emilianomaccaferri** [comment]
Hey thank you!
No I just wanted to add this functionality since the crate itself is really good.

I was only wondering if the crate will have any trouble with HTTPS requests, but I don't think so, right? I didn't investigate yet this option since I'm really early in the project.

**Comment by tomvoet** [comment]
I just added HTTPS functionality, so it should work, see #5

**Comment by emilianomaccaferri** [comment]
super!

**Pull request merged**
