### PR TITLE
exec_query: errors are now returned if the response body contains any

### PR DESCRIPTION
**Pull request by emilianomaccaferri**
Hello there!
I noticed that, when using `rqlite.exec(query)`, if the query produced a database error a 
```
QueryResult {
        last_insert_id: None,
        rows_affected: None,
    }
```
was being returned instead of the actual error.
I tried, for example, to insert a duplicate record and I didn't get the `UNIQUE constraint failed ...` error, but instead I got back (as `Ok`) the `QueryResult` with its fields set to `None`. 
I guess that was because of the implementation of `QueryResult`, that defaulted the values of the `Option`s to `None` when being deserialized.
This is a tentative fix, I didn't test it thoroughly and I don't expect it to solve the issue "completely", I made this pr just to let you know about the bug.

### CODE REVIEW

**Comment by tomvoet** [comment]
Ooh okay good to know!
What do you think would be better: Returning a RequestError(DatabaseError) or just a QueryResult with rows_affected 0?

**Comment by emilianomaccaferri** [comment]
imo the error is better because it's clearer

**Comment by tomvoet** [comment]
Hi, sorry for the long wait - been a bit busy :)
Basically it should work now, lmk how it goes for you.
If everything is okay for you, i'll merge it!

**Comment by emilianomaccaferri** [comment]
wow super clever, I didn't know reordering worked like this

like it tries to parse Error and then Success?

**Comment by tomvoet** [comment]
Yeah, exactly
in case of untagged enums serde deserializes them in order until one deserializes successfully
see https://serde.rs/enum-representations.html#untagged

**Comment by emilianomaccaferri** [comment]
super good to know! contributing to this repo actually helped me start "seriously" using rust haha

**Comment by tomvoet** [comment]
Love to hear that :)
I'll merge this now, I also couldn't find anything wrong with this.
Publishing a new version in a couple minutes

**Pull request merged**
