### PR TITLE
feat: added basic support for blobs

### LINKED ISSUE #14: Add support for `Vec<u8>` in `RqliteArgumentRaw`
See: https://rqlite.io/docs/api/api/#blob-data

Could this crate have support for Blobs ?
Typically `Vec<u8>`

Thank you for this very cool crate !
PS: (I have no idea if it it hard, but no using async in this crate would help me implement it ^^)

### PR DESCRIPTION
**Pull request by tomvoet**
resolves #14

This PR aims to add support for blobs. 
There are two main ways to solve this:

1. Just add the ?blob_array query param (https://rqlite.io/docs/api/api/#blob-data)
2. Add custom logic for parsing base64

Variant 2 is preferable for performance reasons and minimizes request size.

### CODE REVIEW

**Comment by tomvoet** [comment]
What do you think @williamdes, does this match what you imagined?

You can see an example here: https://github.com/tomvoet/rqlite-rs/blob/c8950a2e4e81747fb78522358925f431a95f7a1c/examples/Cargo.toml

**Comment by williamdes** [comment]
Hi @tomvoet !
This really looks good, but can the blob insertion be done without base64 ?
I feel this is an implicit abstraction that may cause confusion

**Comment by tomvoet** [comment]
Thanks for the quick reply @williamdes!

Are you talking about just the insertion or also about select statements and deserialization?

While we can make rqlite respond with u8 arrays for blobs (using the `blob_array` query param), the requests tend to grow larger for significant blob sizes due to added characters like commas. I believe the base64 en- & decoding strikes a good balance by keeping performance overhead minimal while avoiding the need to make additional query parameters mandatory.

What are your thoughts on this? Nonetheless I'll do some testing, to back up the eventual implementation choice here :)

**Comment by tomvoet** [comment]
Hi again,

After some testing, I found that for larger blobs (>250kb [still relatively small]), the request and response payload sizes are approximately 25–33% smaller when using base64 encoding. In my opinion, this reduction in payload size is significant enough to justify keeping the base64 encoding and decoding approach.

The performance overhead from base64 encoding is minimal, and in my experience, scaling for CPU load tends to be easier and more cost-effective than addressing network bandwidth constraints.

What do you think?

**Comment by williamdes** [comment]
Okay, that's great

>While we can make rqlite respond with u8 arrays

I think that some users may not want base64 encoded data in their database. Or need backwards compatibility of reading data from existing dbs. 
can we have a parameter to disable it?

**Comment by tomvoet** [comment]
Ah, my bad—I think I misunderstood you (& the docs) the first time.
I gotta agree encoding to base64 before inserting into the database seems unnecessary. My current plan looks as follows:

1. Insert without base64 encoding to avoid unnecessary transformations and keep backwards compatibilty.
2. Use rqlite's base64 decoding during retrieval to reduce bandwidth usage for larger blobs.

Is this what you were aiming for or am I still missing something?

**Comment by williamdes** [comment]
> Ah, my bad—I think I misunderstood you (& the docs) the first time. I gotta agree encoding to base64 before inserting into the database seems unnecessary. My current plan looks as follows:

No worries

>     1. Insert without base64 encoding to avoid unnecessary transformations and keep backwards compatibilty.

Perfect for me

>     2. Use rqlite's base64 decoding during retrieval to reduce bandwidth usage for larger blobs.

Okay, I think I get it. Between the DB and the API response base64 is used.
Good for me, having a base64 output param could also be handy.

> Is this what you were aiming for or am I still missing something?

I think everything should be fine with this new version

I am trying to port rqlite as a backend for https://github.com/stalwartlabs/mail-server/

**Comment by tomvoet** [comment]
Okay, I was in a bit of a hurry, but hoping I haven't forgotten anything this time :)
The current implementation is as follows:
- Insertion: No encoding.
- Retrieval: Base64-decoding is added if the `fast-blob` feature is enabled. When the feature is disabled, the `blob_array` query param is added automatically and vec[u8s] are retrieved if possible.

Hope this is a little more what you wanted. If I still missed something, please let me know!

**Review by williamdes — APPROVED** [review]
I'd say this all looks good, thank you so much !

**Comment by tomvoet** [comment]
Great! Let me know if there's anything else you need :)
I'll publish a new version asap!

PS.: Happy holidays :)

**Pull request merged**
