### PR TITLE
feat(rqlite-rs): allow optional parameters (#15)

### LINKED ISSUE #15: query macro with Option values
Is it possible, when using a query macro, to pass a value there as an Option argument, so that when Some(val) is inserted, a value is inserted, and when None is NULL

### PR DESCRIPTION
**Pull request by tomvoet**
This PR resolves #15 

It adds support for using options. Take a look at [examples\option.rs](examples\option.rs) for an example (runnable via `cargo r --example option`).

I'd appreciate any feedback! :)

🚨*Warning*: This is includes a breaking change, since `RqliteArgument` was reimplemented from scratch

### CODE REVIEW

**Comment by magwoo** [comment]
it looks good, but at first I expected that you would just add an option to the RqliteArgument structure, something like None or Null:), but your option is probably more correct, I'm also glad to see the implementation of the argument for a string slice, but it's a pity to lose full backward compatibility

**Comment by tomvoet** [comment]
Yeah you're right, I think this is better in the long term though. Also this only hurts backwards compatibility in the very niche case of actually "manually" constructing the RqliteArgument, instead of via one of the macros.

I'm also wondering why I didn't add Options in the first place, it should've probably been implemented from the beginning. So thanks again for bringing this up :)

**Comment by tomvoet** [comment]
Actually, your idea with the Null-variant in the RqliteArgument struct seems pretty smart and a lot easier!
I've created a little draft over at [feature/optional-params-alternative-impl](https://github.com/tomvoet/rqlite-rs/tree/feature/optional-params-alternative-impl).
I feel like this is much better than the original approach. 
Please let me know what you think, and if you think the string slice implementation should also be added (would break backwards compatility for the same niche use case mentioned before).

**Comment by magwoo** [comment]
I would suggest that to stick with semver, you can now release an update for rqlite-rs as version 0.4.0 with a Null value to preserve backward compatibility, and leave the string slices with loss of compatibility for version 1.0.0, while the changes are insignificant for 1.0.0, you can simply postpone them and release them for example as 1.0.0-alpha or something like that

**Pull request closed without merging**
